### ISSUE TITLE
isnt working as expected

### ISSUE THREAD

**Issue by joseehilton147** [macheteHot/unocss-preset-scalpel#3]
before i found your plugin i got this as a postprocess:

// When using text utilities, convert rem to px
if (/^\.text-(xs|sm|base|lg|xl|[2-9]xl)$/.test(util.selector)) {
util.entries.forEach(i => {
	const value = i[1].toString()
	i[1] = `${+value.slice(0, -3) * 16}px`
})
} else {
// convert rem to px for everything except text utilities
util.entries.forEach(i => {
	const value = i[1].toString()
	if (/^-?[.\d]+rem$/.test(value)) i[1] = `${+value.slice(0, -3) * 4}px`
})
}

so when i only add like w-100 instead using rem use px and is working perfect. example:

![image](https://user-images.githubusercontent.com/53986027/230187979-e97ffcec-2b70-4bdb-984a-4246eeda2c81.png)

so i remove my code and add your preset, and isnt set the default unit to px

![image](https://user-images.githubusercontent.com/53986027/230188211-d6f00c85-99e0-4f45-99d6-cd386c5a1e01.png)
![image](https://user-images.githubusercontent.com/53986027/230189263-c9597248-7814-4cae-b295-27092655ea07.png)

using rem instead px

only thing i did is just comment my code.

Am i doing something wrong?

my code:

import {presetScalpel} from 'unocss-preset-scalpel'
presets: [presetUno({}), presetScalpel({})],

im using unocss 0.50.5 and nuxt 3.3.3

**Comment by macheteHot** [comment]
if you want convert util you can use  special `v` and config 

```
vToAny: {
    unit: 'rem', // convert v to rem
    rootValue: 16, // value ÷ this
    unitPrecision: 5,
    minPixelValue: 1,
  }
```

or set default unit is `v`
```
{
  unit:'v',
}
```
then you can use like `fs-12v`

**Comment by joseehilton147** [comment]
i update my code to following your structure, like instead py p-y

but i find a problem:

![image](https://user-images.githubusercontent.com/53986027/230397671-85ed6d4a-66bd-4d70-b915-ff387a424949.png)

you dont support text-2xl for example, see image, there's a way to use it? like converting te rem to px like i do in my code above using regex?

**Comment by macheteHot** [comment]
> 

yes relative is not support, but i think u can add custom rule in  [unocss](https://unocss.dev/config/rules)
