### ISSUE TITLE
color-yellow-4 isnt being respected

### ISSUE THREAD

**Issue by joseehilton147** [macheteHot/unocss-preset-scalpel#4]
this dont work:

![image](https://user-images.githubusercontent.com/53986027/230428347-92b7c28a-8dd3-49d3-becb-60f612a4ac67.png)

this work:

![image](https://user-images.githubusercontent.com/53986027/230428711-20cec89a-967c-42b6-88c7-538c556cde0e.png)

if this suppose to happen?

if you go to uno interactive color-yellow-4 and color-yellow-400 has the same output

https://unocss.dev/interactive/?s=color-yellow-4
https://unocss.dev/interactive/?s=color-yellow-400

by the way loved your project, should be part of uno have this dynamism

**Comment by macheteHot** [comment]
Actually the yello-4 mean color is yellow but opacity is 4% ,and if you want add custom color you should config like this
```
{
  /**
   * define color name
   */
  colors:{
    yellow1: '#xxx',
    yellow2: '#xxx',
    ...
  },
```
then u can use like `c-yellow1` `text-yellow1`
