### ISSUE TITLE
how to apply border radius to top or bottom only?

### ISSUE THREAD

**Issue by joseehilton147** [macheteHot/unocss-preset-scalpel#5]
![image](https://user-images.githubusercontent.com/53986027/230434966-3776add2-6552-4e8d-8a69-ac399615be04.png)

i want to do this:

https://unocss.dev/interactive/?s=b-rd-t-16

its possible?

**Comment by macheteHot** [comment]
yes is possible in future , is will be soon

**Comment by macheteHot** [comment]
u can upgrade to 1.2.7
